
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pruebacup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int metodo = 2;
  public static final int Pcierra = 20;
  public static final int nombre = 12;
  public static final int args = 5;
  public static final int decimal = 8;
  public static final int coma = 16;
  public static final int llave_abre = 13;
  public static final int imprime = 3;
  public static final int llave_cierra = 14;
  public static final int Ccierra = 18;
  public static final int mensage = 11;
  public static final int igual = 9;
  public static final int EOF = 0;
  public static final int dec = 22;
  public static final int signo = 21;
  public static final int Cabre = 17;
  public static final int Pabre = 19;
  public static final int lectura = 10;
  public static final int error = 1;
  public static final int entero = 7;
  public static final int ent = 23;
  public static final int principal = 4;
  public static final int punto_coma = 15;
  public static final int operacion = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "metodo",
  "imprime",
  "principal",
  "args",
  "operacion",
  "entero",
  "decimal",
  "igual",
  "lectura",
  "mensage",
  "nombre",
  "llave_abre",
  "llave_cierra",
  "punto_coma",
  "coma",
  "Cabre",
  "Ccierra",
  "Pabre",
  "Pcierra",
  "signo",
  "dec",
  "ent"
  };
}

